### ISSUE TITLE
Unnecessary .vscode folder?

### ISSUE THREAD

**Issue by MonliH** [binkiklou/Chirp#22]
## Bug description
Why is there a [`.vscode`](https://github.com/binkiklou/Chirp/tree/master/.vscode) folder? I think this happened because someone used VSCode, and forgot to put it into the `.gitignore` file. This is an (what I think) unnecessary folder. I'm not sure if this is intentional, since some people use the folder to [share config settings](https://stackoverflow.com/a/32979933), but that seems unlikely.

## Fix
Delete the `.vscode` folder?
Add `.vscode/` into the `.gitignore` file?

**Comment by binkiklou** [comment]
I put it there on purpose, so you can use vscode to compile & debug the project easily.
